[project]
name = "modflow6"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
version = "6.5.0.dev2"

[dependencies]
appdirs = "*"
filelock = "*"
flaky = "*"
fortran-language-server = "*"
fprettify = "*"
hatchling = "*"
jupytext = "*"
matplotlib = "*"
meson = "1.3.0"
mfpymake = "*"
networkx = "*"
ninja = "*"
numpy = "*"
pandas = "*"
pip = "*"
pydotplus = "*"
pyshp = "*"
pytest = "!=8.1.0"
pytest-benchmark = "*"
pytest-dotenv = "*"
pytest-order = "*"
pytest-xdist = "*"
python = "3.9.*"
requests = "*"
scipy = "*"
shapely = "*"
xmipy = "*"

[pypi-dependencies]
flopy = { git = "https://github.com/modflowpy/flopy.git" }
modflowapi = { git = "https://github.com/MODFLOW-USGS/modflowapi.git" }
modflow-devtools = { git = "https://github.com/MODFLOW-USGS/modflow-devtools.git" }

[tasks]
# format
fortran-format-check = "python .github/common/fortran_format_check.py"
msvs-vfproj-check = "python .github/common/msvs_vfproj_check.py"

# build/test
setup = "meson setup --prefix=$(pwd) --libdir=bin"
build = "meson install -C"
test = "meson test --verbose --no-rebuild -C"
update-flopy = { cmd = "python update_flopy.py", cwd = "autotest" }
get-exes = { cmd = "pytest -v --durations 0 get_exes.py", cwd = "autotest" }
autotest = { cmd = "pytest -v -n auto --durations 0 --keep-failed .failed", cwd = "autotest" }

# dist/docs
benchmark = { cmd = "python benchmark.py", cwd = "distribution" }
build-docs = { cmd = "python build_docs.py", cwd = "distribution" }
build-dist = { cmd = "python build_dist.py", cwd = "distribution" }
build-makefiles = { cmd = "python build_makefiles.py", cwd = "distribution" }
test-dist-scripts = { cmd = "pytest -v --durations 0", cwd = "distribution" }
update-version = { cmd = "python update_version.py", cwd = "distribution" }
mk-folder-struct = { cmd = "python mk_folder_struct.py", cwd = "doc/ReleaseNotes" }
deprecations = { cmd = "python deprecations.py", cwd = "doc/mf6io/mf6ivar" }
sphinx = { cmd = "make html", cwd = ".build_rtd_docs" }