name: Test parallel MF6 (Windows)
description: Build and test parallel MODFLOW 6 on Windows
runs:
  using: "composite"
  steps:

    - name: Build MF6 parallel
      uses: ./modflow6/.github/actions/build-par-win

    - name: Update flopy
      working-directory: modflow6
      shell: cmd
      run: pixi run update-flopy

    - name: Get executables
      working-directory: modflow6/autotest
      shell: cmd
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: pixi run get-exes

    - name: Test programs
      shell: cmd 
      env:
        REPOS_PATH: ${{ github.workspace }}
      run: |
        unix2dos -n "%GITHUB_WORKSPACE%\modflow6\.github\common\test_modflow6.bat" "%TEMP%\test_modflow6.bat"
        "%ONEAPI_ROOT%\setvars.bat" intel64 vs2022 && "%TEMP%\test_modflow6.bat"
