name: Build parallel MF6 (Windows)
description: Build parallel MODFLOW 6 on Windows
runs:
  using: "composite"
  steps:

    - name: Setup PETSc
      uses: ./modflow6/.github/actions/build-petsc-win

    - name: Build modflow6
      shell: cmd
      run: |
        unix2dos -n "%GITHUB_WORKSPACE%\modflow6\.github\common\compile_modflow6.bat" "%TEMP%\compile_modflow6.bat"
        "%ONEAPI_ROOT%\setvars.bat" intel64 vs2022 && "%TEMP%\compile_modflow6.bat"

    - name: Show Meson logs
      if: failure()
      shell: bash
      working-directory: modflow6
      run: cat builddir/meson-logs/meson-log.txt