[sections]
features = "NEW FUNCTIONALITY"
fixes = "BUG FIXES AND OTHER CHANGES TO EXISTING FUNCTIONALITY"
examples = "EXAMPLES"

[subsections]
basic = "BASIC FUNCTIONALITY"
internal = "INTERNAL FLOW PACKAGES"
stress = "STRESS PACKAGES"
advanced = "ADVANCED STRESS PACKAGES"
solution = "SOLUTION"
exchanges = "EXCHANGES"
parallel = "PARALLEL"

[[items]]
section = "features"
subsection = "basic"
description = "The binary grid file's name may now be specified in all discretization packages with option GRB6 FILEOUT followed by a file path. If this option is not provided, the binary grid file will be named as before, identical to the discretization file name plus a ``.grb'' extension. Note that renaming the binary grid file may break downstream integrations which expect the default name."

[[items]]
section = "examples"
description = "A new example was added demonstrating transient thermal loading of multiple borehole heat exchangers with the Groundwater Energy (GWE) model. The simulated GWE results match the temperature change predicted by the analytical solution for the multiple borehole heat exchangers used in this problem."

[[items]]
section = "features"
subsection = "internal"
description = "Added interbed-compaction-pct observation to the CSUB package."

[[items]]
section = "fixes"
description = "The mf6io.pdf guide for the SFE Package lists the availability of the STRMBD-COND observation type.  However, the SFE Package did not actually support this observation type and if listed would cause the program to exit with error message.  Functionality has been added to SFE for writing the amount of streambed conductive heat exchange to the CSV output file that contains the user-specified observations."
