[sections]
features = "NEW FUNCTIONALITY"
fixes = "BUG FIXES AND OTHER CHANGES TO EXISTING FUNCTIONALITY"
examples = "EXAMPLES"

[subsections]
basic = "BASIC FUNCTIONALITY"
internal = "INTERNAL FLOW PACKAGES"
stress = "STRESS PACKAGES"
advanced = "ADVANCED STRESS PACKAGES"
solution = "SOLUTION"
exchanges = "EXCHANGES"
parallel = "PARALLEL"

[[items]]
section = "fixes"
subsection = "internal"
description = "Fixed first-order decay in GWT so that production/decay does not occur when aqueous or sorbed concentration are negative."

[[items]]
section = "features"
subsection = "basic"
description = "Add a discretization text input option CRS for a real-world model coordinate reference system, for example, an EPSG integer code, authority string, or Open Geospatial Consortium Well-Known Text (WKT) specification. The entry for CRS does not affect the model simulation, but it is written to a version 2 binary grid file so that postprocessors can locate the grid in space."

[[items]]
section = "fixes"
subsection = "basic"
description = "GWT-IST package input tags have been changed for two record options. Until now the CIM keyword was used for both FILEOUT and PRINT\_FORMAT input record options. This update changes the FILEOUT keyword tag to CIM6 and the PRINT\_FORMAT keyword tag to CIMFMT. These changes will impact existing MODFLOW 6 GWT-IST input files using these options. The behavior of these two options should otherwise not be impacted."
