[sections]
features = "NEW FUNCTIONALITY"
fixes = "BUG FIXES AND OTHER CHANGES TO EXISTING FUNCTIONALITY"
examples = "EXAMPLES"

[subsections]
basic = "BASIC FUNCTIONALITY"
internal = "INTERNAL FLOW PACKAGES"
stress = "STRESS PACKAGES"
advanced = "ADVANCED STRESS PACKAGES"
solution = "SOLUTION"
exchanges = "EXCHANGES"
parallel = "PARALLEL"

[[items]]
section = "fixes"
subsection = "internal"
description = "Fixed first-order decay in GWT so that production/decay does not occur when aqueous or sorbed concentration are negative."

[[items]]
section = "features"
subsection = "basic"
description = "Add a discretization text input option CRS for a real-world model coordinate reference system, for example, an EPSG integer code, authority string, or Open Geospatial Consortium Well-Known Text (WKT) specification. The entry for CRS does not affect the model simulation, but it is written to a version 2 binary grid file so that postprocessors can locate the grid in space."

[[items]]
section = "features"
subsection = "stress"
description = "Add HIGHEST\\_SATURATED option to the GWT SRC package. When activated, the HIGHEST\\_SATURATED option will apply a mass source loading rate to the specified CELLID or the highest underlying cell with a non-zero cell saturation. The HIGHEST\\_SATURATED option has an additional complication for certain types of grids specified using the DISU Package. When the DISU Package is used, a cell may have more than one cell underlying it. If the overlying cell were to become inactive, there is no straightforward method for determining how to apportion the mass source loading rate to the underlying cells. In this case, the approach described by \\cite{modflowusg} is used. The mass source loading rate is assigned to the first active cell encountered (determined by searching through the underlying cell numbers from the lowest number to the highest number). In this manner, the total mass source loading rate is conserved; however, the spatial distribution of the applied mass source loading rate may not be maintained as layers become dry or wet during a simulation."
