name: Build NetCDF (Windows)
description: Build NetCDF on Windows
runs:
  using: "composite"
  steps:

    - name: Convert line endings
      shell: cmd
      run: |
        unix2dos -n "%GITHUB_WORKSPACE%\modflow6\.github\common\compile_netcdf.bat" "%TEMP%\compile_netcdf.bat"

    - name: Install latest cmake and ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latest
        ninjaVersion: latest

    - name: Setup oneAPI
      uses: ./modflow6/.github/actions/setup-par-oneapi

    - name: Setup 7-zip
      uses: milliewalky/setup-7-zip@v1

    - name: Prepare for NetCDF-C download
      shell: bash
      run: |
        mkdir -p netcdf/netCDF4.9.2-NC4-64

    - name: Download NetCDF-C
      uses: nick-fields/retry@v3
      with:
        shell: bash
        timeout_minutes: 1
        max_attempts: 5
        retry_on: error
        command: |
          curl -L -o netcdf/netCDF4.9.2-NC4-64/netCDF4.9.2-NC4-64.exe "https://downloads.unidata.ucar.edu/netcdf-c/4.9.2/netCDF4.9.2-NC4-64.exe"

    - name:  Unpack NetCDF-C download
      working-directory: netcdf/netCDF4.9.2-NC4-64
      shell: bash
      run: |
        7z x netCDF4.9.2-NC4-64.exe -aou

    - name: Prepare for NetCDF-Fortran download
      shell: bash
      run: |
        mkdir -p netcdf/netcdf-fortran-4.6.1/build

    - name: Download NetCDF-Fortran
      uses: nick-fields/retry@v3
      with:
        shell: bash
        timeout_minutes: 1
        max_attempts: 5
        retry_on: error
        command: |
          curl -L -o netcdf/netcdf-fortran-4.6.1/netcdf-fortran-4.6.1.zip "https://downloads.unidata.ucar.edu/netcdf-fortran/4.6.1/netcdf-fortran-4.6.1.zip"

    - name: Unzip NetCDF-Fortran download
      working-directory: netcdf/netcdf-fortran-4.6.1
      shell: bash
      run: |
        unzip netcdf-fortran-4.6.1.zip

    - name: Build NetCDF
      shell: cmd
      run: |
        "%ONEAPI_ROOT%\setvars.bat" intel64 vs2022 && "%TEMP%\compile_netcdf.bat"
