import argparse
from os import PathLike
import sys
import textwrap
from pathlib import Path
from pprint import pprint
from typing import Optional

import yaml
from jinja2 import Environment, FileSystemLoader

from modflow_devtools.dfn import Dfn

from filters import Filters

MF6_LENVARNAME = 16
F90_LINELEN = 82
PROJ_ROOT_PATH = Path(__file__).parents[3]
DEFAULT_DFNS_PATH = Path(__file__).parents[1] / "dfns.txt"
DFN_PATH = PROJ_ROOT_PATH / "doc" / "mf6io" / "mf6ivar" / "dfn"
SRC_PATH = PROJ_ROOT_PATH / "src"
IDM_PATH = SRC_PATH / "Idm"


def _get_template_env():
    template_loader = FileSystemLoader(Path(__file__).parent)
    template_env = Environment(
    loader=template_loader,
    trim_blocks=True,
    lstrip_blocks=True,
    line_statement_prefix="_",
    keep_trailing_newline=True,
    )
    template_env.filters["value"] = Filters.value
    return template_env


def make_targets(dfn, outdir: PathLike, verbose: bool = False):
    # TODO component file
    # TODO selector file
    pass


def make_all(dfndir: PathLike, outdir: PathLike, verbose: bool = False, version: int = 1):
    """Generate Fortran source files from DFN files."""
    # TODO all component and selector files
    # TODO master selector file
    pass


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="Convert DFN files to Fortran source files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent(
            """\
            Generate Fortran source code from DFN files. This script
            converts definition (DFN) files to Fortran source files,
            each representing a parameter set for a particular input
            definition. Fortran files generated by this tool provide
            support for simulations, models or packages described by
            the given DFN files. Each DFN file is transformed into a
            corresponding Fortran file with "idm" and the same stem:
            e.g. gwf-ic.dfn becomes gwf-icidm.f90.
            """
        ),
    )
    parser.add_argument(
        "-d",
        "--dfn",
        required=False,
        default=DEFAULT_DFNS_PATH,
        help="Path to a DFN file, a directory containing DFN files, or to a text or YAML file listing DFN files (one per line)",
    )
    parser.add_argument(
        "-o",
        "--outdir",
        required=False,
        default=IDM_PATH,
        help="The directory to write Fortran source files",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        required=False,
        default=False,
        help="Whether to show verbose output",
    )
    args = parser.parse_args()
    dfn = Path(args.dfn)
    outdir = Path(args.outdir) if args.outdir else Path.cwd()
    verbose = args.verbose

    if dfn.suffix.lower() in [".txt"]:
        dfns = open(dfn, "r").readlines()
        dfns = [l.strip() for l in dfns]
        dfns = [l for l in dfns if not l.startswith("#") and l.lower().endswith(".dfn")]
        if dfn == DEFAULT_DFNS_PATH:
            dfns = [DFN_PATH / p for p in dfns]
    elif dfn.suffix.lower() in [".yml", ".yaml"]:
        dfns = yaml.safe_load(open(dfn, "r"))
    elif dfn.suffix.lower() in [".dfn"]:
        dfns = [dfn]

    assert all(p.is_file() for p in dfns), (
        f"DFNs not found: {[p for p in dfns if not p.is_file()]}"
    )

    if verbose:
        print("Converting DFNs:")
        pprint(dfns)

    
    # TODO make targets