name: fortran-format-check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  fortan-format-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        with:
            cache-downloads: true
            cache-env: true

      - name: Install gfortran
        uses: modflowpy/install-gfortran-action@v1

      - name: Print python package versions
        run: |
          pip list

      - name: Set and print branch name
        run: |
          .github/common/git-branch-export.sh

      - name: Fortran source format check
        run: |
          .github/common/fortran-format-check.sh
