name: Pull Request Docs Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: .build_rtd_docs

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip and install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{env.working-directory}}

    - name: run sphinx
      run: |
        make html
      working-directory: ${{env.working-directory}}

    - name: list files
      shell: bash
      run: |
        ls -lh _mf6io/
      working-directory: ${{env.working-directory}}

    # Great extra actions to compose with:
    # Create an artifact of the processed files.
    - uses: actions/upload-artifact@v1
      with:
        name: rtd-files-for-${{ github.sha }}
        path: |
          ${{env.working-directory}}/_mf6io/
          ${{env.working-directory}}/_static/
          ${{env.working-directory}}/mf6io.rst
